## Часть 1: Введение в Pandas

Pandas - это библиотека Python для работы с данными. Она предоставляет мощные инструменты для анализа и манипуляции данными.

### Установка Pandas

Для начала убедитесь, что у вас установлена библиотека Pandas. Если ее нет, установите ее с помощью команды:

In [1]:
#!pip install pandas

## Импорт библиотеки
Давайте начнем с импорта библиотеки Pandas:

In [1]:
import pandas as pd

## Часть 2: Работа с данными
### Чтение данных
Мы будем использовать датасет Titanic. Давайте прочитаем данные из CSV файла.

In [13]:
# Чтение данных из файла 'titanic.csv'
# Используйте метод pd.read_csv()
titanic_ds = pd.read_csv('titanic.csv')
titanic_ds

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### Предпросмотр данных
Для первого ознакомления с данными давайте выведем первые несколько строк.

In [4]:
# Вывод первых 5 строк данных
# Используйте метод .head()
titanic_ds.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Информация о данных
Чтобы получить общую информацию о данных, воспользуйтесь методом .info().

In [5]:
titanic_ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

### Работа с NaN
Часто данные содержат пропущенные значения, которые представляются как NaN (Not a Number). Pandas предоставляет удобные методы для работы с ними.

Проверка на наличие NaN. Методы fillna и dropna возвращают новые Dataframe, проверьте нет ли в них NaN

In [27]:
# Проверка на наличие NaN в DataFrame
# Используйте метод .isna()
print(titanic_ds.isna())
print(titanic_ds.isna().sum())

     PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False
1          False     False   False  False  False  False  False  False   False
2          False     False   False  False  False  False  False  False   False
3          False     False   False  False  False  False  False  False   False
4          False     False   False  False  False  False  False  False   False
..           ...       ...     ...    ...    ...    ...    ...    ...     ...
886        False     False   False  False  False  False  False  False   False
887        False     False   False  False  False  False  False  False   False
888        False     False   False  False  False   True  False  False   False
889        False     False   False  False  False  False  False  False   False
890        False     False   False  False  False  False  False  False   False

      Fare  Cabin  Embarked
0    False   True     False
1    False  False     False
2    False   True     False
3    False  False     False
4    False   True     False
..     ...    ...       ...
886  False   True     False
887  False  False     False
888  False   True     False
889  False  False     False
890  False   True     False

[891 rows x 12 columns]
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Заполнение NaN

In [41]:
# Заполнение NaN определенным значением (например, нулем)
# Используйте метод .fillna()
titanic_ds.fillna(0)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,0,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,0,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,0,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,0,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,0.0,1,2,W./C. 6607,23.4500,0,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,0,Q

Удаление строк с NaN

In [42]:
# Удаление строк, содержащих NaN
# Используйте метод .dropna()
titanic_ds.dropna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

## Часть 3: Обработка DataFrame
### Выбор данных
Pandas позволяет выбирать данные по индексам, меткам столбцов и условиям.

In [50]:
# Выбор столбца по метке
# Используйте синтаксис DataFrame['название_столбца']
print(titanic_ds['Name'])

# Выбор нескольких столбцов
# Используйте синтаксис DataFrame[['столбец_1', 'столбец_2']]
print(titanic_ds[['Age', 'Cabin']])

# Выбор строк по индексу
# Используйте метод .loc[]
print(titanic_ds.loc[12])

# Выбор строк и столбцов по условию
# Используя логические операции, выберите мужчин старше 30
print(titanic_ds[(titanic_ds['Sex']=='male') & (titanic_ds['Age']>30)])

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object
      Age Cabin
0    22.0   NaN
1    38.0   C85
2    26.0   NaN
3    35.0  C123
4    35.0   NaN
..    ...   ...
886  27.0   NaN
887  19.0   B42
888   NaN   NaN
889  26.0  C148
890  32.0   NaN

[891 rows x 2 columns]
PassengerId                                13
Survived                                    0
Pclass                                      3
Name           Saundercock, Mr. William Henry
Sex                                      male
Age                                      20.0
SibSp                                       0
Parch                                       0
Ticket                              A/5. 2151
Fare                                     8.05
Cabin                                     NaN
Embarked                                    S
Name: 12, dtype: object
     PassengerId  Survived  Pclass                                  Name  \
4              5         0       3              Allen, Mr. William Henry
6              7         0       1               McCarthy, Mr. Timothy J
13            14         0       3           Andersson, Mr. Anders Johan
20            21         0       2                  Fynney, Mr. Joseph J
21            22         1       2                 Beesley, Mr. Lawrence
..           ...       ...     ...                                   ...
867          868         0       1  Roebling, Mr. Washington Augustus II
872          873         0       1              Carlsson, Mr. Frans Olof
873          874         0       3           Vander Cruyssen, Mr. Victor
881          882         0       3                    Markun, Mr. Johann
890          891         0       3                   Dooley, Mr. Patrick

      Sex   Age  SibSp  Parch    Ticket     Fare        Cabin Embarked
4    male  35.0      0      0    373450   8.0500          NaN        S
6    male  54.0      0      0     17463  51.8625          E46        S
13   male  39.0      1      5    347082  31.2750          NaN        S
20   male  35.0      0      0    239865  26.0000          NaN        S
21   male  34.0      0      0    248698  13.0000          D56        S
..    ...   ...    ...    ...       ...      ...          ...      ...
867  male  31.0      0      0  PC 17590  50.4958          A24        S
872  male  33.0      0      0       695   5.0000  B51 B53 B55        S
873  male  47.0      0      0    345765   9.0000          NaN        S
881  male  33.0      0      0    349257   7.8958          NaN        S
890  male  32.0      0      0    370376   7.7500          NaN        Q

[202 rows x 12 columns]

### Сортировка данных
Сортировка данных по значениям столбцов.

In [57]:
# Сортировка данных по столбцу 'столбец_1' по возрастанию
# Используйте метод .sort_values()
titanic_ds.sort_values('Age').head(15)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
831,832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,NaN,S
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
386,387,0,3,"Goodwin, Master. Sidney Leonard",male,1.00,5,2,CA 2144,46.9000,NaN,S
172,173,1,3,"Johnson, Miss. Eleanor Ileen",female,1.00,1,1,347742,11.1333,NaN,S
183,184,1,2,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,F4,S
164,165,0,3,"Panula, Master. Eino Viljami",male,1.00,4,1,3101295,39.6875,NaN,S
827,828,1,2,"Mallet, Master. Andre",male,1.00,0,2,S.C./PARIS 2079,37.0042,NaN,C
788,789,1,3,"Dean, Master. Bertram Vere",male,1.00,1,2,C.A. 2315,20.5750,NaN,S
381,382,1,3,"Nakid, Miss. Maria (""Mary"")",female,1.00,0,2,2653,15.7417,NaN,C
642,643,0,3,"Skoog, Miss. Margit Elizabeth",female,2.00,3,2,347088,27.9000,NaN,S

### Группировка данных
Pandas также позволяет группировать данные и выполнять агрегирующие операции.

In [101]:
# Найдите долю выживших среди всех PClass
# Используйте метод .groupby()
titanic_ds.groupby('Pclass', as_index=False)['Survived'].aggregate(['count', 'sum', 'mean']).rename(columns={'count':'total_count', 'sum':'survivors_number', 'mean':'percent_survivors'})

   Pclass  total_count  survivors_number  percent_survivors
0       1          216               136           0.629630
1       2          184                87           0.472826
2       3          491               119           0.242363

## Часть 4: Задания для практики
Прочитайте данные из файла 'titanic.csv'.
Проверьте, есть ли пропущенные значения в данных и заполните их нулями.
Выведите первые 10 строк данных.
Выберите только те строки, где значение в столбце 'Age' больше 30.
Отсортируйте данные по столбцу 'Fare' в порядке убывания.
Сгруппируйте данные по столбцу 'Pclass' и вычислите средний возраст ('Age') для каждого класса.

In [100]:
df = pd.read_csv('titanic.csv')
print('Пропущенные значения:\n')
print(df.isna().sum())

print('\nЗаполним нулями:\n')
df = df.fillna(0)
print(df.isna().sum())

print('\nПервые 10 строк данных:\n')
print(df.head(10))

print('\nСтроки со значением \'Age\' > 30:\n')
print(df[(df['Age']>30)])

print('\nСортировка по убыванию \'Fare\':\n')
print(df.sort_values('Fare', ascending=False))

print('\nГруппировка по \'Pclass\':\n')
print(df.groupby('Pclass', as_index=False)['Age'].aggregate(['mean']).rename(columns={'mean':'mean_age'}))

Пропущенные значения:

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Заполним нулями:

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

Первые 10 строк данных:

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3
5            6         0       3
6            7         0       1
7            8         0       3
8            9         1       3
9           10         1       2

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0
5                                   Moran, Mr. James    male   0.0      0
6                            McCarthy, Mr. Timothy J    male  54.0      0
7                     Palsson, Master. Gosta Leonard    male   2.0      3
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500     0        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250     0        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500     0        S
5      0            330877   8.4583     0        Q
6      0             17463  51.8625   E46        S
7      1            349909  21.0750     0        S
8      2            347742  11.1333     0        S
9      0            237736  30.0708     0        C

Строки со значением 'Age' > 30:

     PassengerId  Survived  Pclass  \
1              2         1       1
3              4         1       1
4              5         0       3
6              7         0       1
11            12         1       1
..           ...       ...     ...
873          874         0       3
879          880         1       1
881          882         0       3
885          886         0       3
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
6                              McCarthy, Mr. Timothy J    male  54.0      0
11                            Bonnell, Miss. Elizabeth  female  58.0      0
..                                                 ...     ...   ...    ...
873                        Vander Cruyssen, Mr. Victor    male  47.0      0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0
881                                 Markun, Mr. Johann    male  33.0      0
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch    Ticket     Fare Cabin Embarked
1        0  PC 17599  71.2833   C85        C
3        0    113803  53.1000  C123        S
4        0    373450   8.0500     0        S
6        0     17463  51.8625   E46        S
11       0    113783  26.5500  C103        S
..     ...       ...      ...   ...      ...
873      0    345765   9.0000     0        S
879      1     11767  83.1583   C50        C
881      0    349257   7.8958     0        S
885      5    382652  29.1250     0        Q
890      0    370376   7.7500     0        Q

[305 rows x 12 columns]

Сортировка по убыванию 'Fare':

     PassengerId  Survived  Pclass                                Name  \
679          680         1       1  Cardeza, Mr. Thomas Drake Martinez
258          259         1       1                    Ward, Miss. Anna
737          738         1       1              Lesurer, Mr. Gustave J
88            89         1       1          Fortune, Miss. Mabel Helen
438          439         0       1                   Fortune, Mr. Mark
..           ...       ...     ...                                 ...
806          807         0       1              Andrews, Mr. Thomas Jr
815          816         0       1                    Fry, Mr. Richard
466          467         0       2               Campbell, Mr. William
481          482         0       2    Frost, Mr. Anthony Wood "Archie"
822          823         0       1     Reuchlin, Jonkheer. John George

        Sex   Age  SibSp  Parch    Ticket      Fare        Cabin Embarked
679    male  36.0      0      1  PC 17755  512.3292  B51 B53 B55        C
258  female  35.0      0      0  PC 17755  512.3292            0        C
737    male  35.0      0      0  PC 17755  512.3292         B101        C
88   female  23.0      3      2     19950  263.0000  C23 C25 C27        S
438    male  64.0      1      4     19950  263.0000  C23 C25 C27        S
..      ...   ...    ...    ...       ...       ...          ...      ...
806    male  39.0      0      0    112050    0.0000          A36        S
815    male   0.0      0      0    112058    0.0000         B102        S
466    male   0.0      0      0    239853    0.0000            0        S
481    male   0.0      0      0    239854    0.0000            0        S
822    male  38.0      0      0     19972    0.0000            0        S

[891 rows x 12 columns]

Группировка по 'Pclass':

   Pclass   mean_age
0       1  32.923241
1       2  28.091467
2       3  18.177026